# -*- coding: utf-8 -*-
"""python_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYrUyNtIOtfXDKHB54HgZZlq-Bq3QdJm
"""

import numpy as np
a =np.array([[0,1],[2,3],[4,5]])
b = np.array([[0,1,2,3],[4,5,6,7]])
c= a.dot(b)
print(c)
print(c.max())